### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ma-jahn**
This PR covers the following:

Integration of PR's:

- https://github.com/Akryum/vue-cli-plugin-ssr/pull/124

- https://github.com/Akryum/vue-cli-plugin-ssr/pull/110

- https://github.com/Akryum/vue-cli-plugin-ssr/pull/106

- https://github.com/Akryum/vue-cli-plugin-ssr/pull/93

Updating Dependencies:

- eslint 4.13.1 => 6.2.1
- eslint-config-standard 11.0.0 => 14.0.1
- eslint-plugin-import 2.13.0 => 2.13.0
- eslint-plugin-node 7.0.1 => 9.1.0
- eslint-plugin-promise 3.8.0 => 4.2.1
- eslint-plugin-standard 3.1.0 => 4.0.1

### CODE REVIEW

**Review by svewag — COMMENTED** [review]
please merge https://github.com/Akryum/vue-cli-plugin-ssr/pull/41 also

**Comment by partounian** [comment]
@sumcumo @ma-jahn please take a look at the comment above 😄 

Also thank you so much for doing all you've done so far

**Comment by ma-jahn** [comment]
Hi @partounian 

thank you for letting me know. Being honest i overlooked the request. I'll start right now and a update will be available very soon ;)

**Comment by svewag** [comment]
But isn't it already merged?

https://github.com/sumcumo/vue-cli-plugin-ssr/blob/master/lib/dev-server.js

**Comment by ma-jahn** [comment]
Yes it is. https://github.com/sumcumo/vue-cli-plugin-ssr/pull/2

Just haven't tagged it here but it was published within 0.6.0.
I'll now go through all open MR's ;)

**Comment by partounian** [comment]
You guys are awesome!🔥

Please excuse any typos as I'm sending this message from my phone.

**Comment by partounian** [comment]
I can't figure out how to use `vue add` with this, or install it manually then use `vue invoke`. Any chance somehow can tell me how to use this package?

**Comment by ma-jahn** [comment]
Yeah.. You need to set it up manually. There is a bug within vue shared utils which doesn't allow package scopes containing a dot. Therefore our package can not be detected.
Our MR was already merged but not yet released. 

I am currently in vacation and will update our Readme to show you what you need to do.

Cheers

**Pull request merged**
